### ISSUE TITLE
juju dhx does not work when I have no configuration file

### ISSUE THREAD

**Issue by mbruzek** [juju/plugins#45]
I am trying to use the juju-dhx plugin and I encountered a reproducable error.  When I have no configuration file the `juju dhx` command returns the error:

error: no ssh key id specified
ERROR subprocess encountered error code 2

Adding a configuration file resolves this problem.  Please handle the case where no configuration file exists.

**Comment by johnsca** [comment]
Specifically, it's calling (the API behind) `juju authorized-keys import` with an empty list, which fails.
